site_name: Snake Game
site_description: Un juego clásico de la serpiente con gestión de perfiles y configuraciones.
site_url: https://ParaDevOne.github.io/snake

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

plugins:
  - mkdocstrings
  - search

nav:
  - Inicio: index.md
  - Guía: guide.md
  - API: reference.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superf
